#!/usr/bin/zsh

file=$1
w=$2
h=$3
x=$4
y=$5
filetype="$(file --dereference --brief --mime-type -- "$1")"

case $filetype in
    image/*)
        chafa -f sixel -s "$2x$3" --animate off --polite on "$1"
        ;;
    text/html) 
        lynx -width="$4" -display_charset=utf-8 -dump "$1"
        ;;
    text/troff) 
        man ./ "$1" | col -b 
        ;;
    text/* | */xml | application/json | application/x-ndjson | application/javascript)
        bat --terminal-width "$(($4-2))" -f "$1" 
        ;;
    audio/* | application/octet-stream)
        mediainfo "$1"
        ;;
    */pdf)
        pdftoppm -jpeg -f 1 -singlefile "$file" "$XDG_CACHE_HOME/tmpimg"
        chafa -f sixel -s "$2x$3" --animate off --polite on "$XDG_CACHE_HOME/tmpimg.jpg"
        ;;
    application/*zip)
        atool --list -- "$1"
        ;;
    *opendocument*)
        odt2txt "$1"
        ;;
    application/pgp-encrypted)
        gpg -d -- "$1"
        ;;
esac
