theme = "solarized_dark"

[editor]
mouse = true
cursor-shape = { insert = "bar" }
#indent = 4
color-modes = true
true-color = true
soft-wrap.enable = true
indent-guides.render = true
#indent-guides.skip-levels = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
