theme = "solarized_dark"

[editor]
mouse = true
# indent = 4
color-modes = true
true-color = true
soft-wrap.enable = true
indent-guides.render = true
# indent-guides.skip-levels = true
auto-format = true
auto-completion = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
auto-signature-help = false
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"#" = "toggle_comments"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
