colors:
  body: none
  date: black
  tags: yellow
  title: cyan
default_hour: 12
default_minute: 0
editor: helix
encrypt: false
highlight: true
indent_character: '|'
journals:
  default:
    journal: /home/ilyss/.local/share/jrnl/journal.txt
linewrap: 79
tagsymbols: '#@'
template: false
timeformat: '%X %x'
version: v4.1
