colors:
  body: none
  date: black
  tags: yellow
  title: cyan
default_hour: 12
default_minute: 0
editor: nvim
encrypt: false
highlight: true
indent_character: '|'
journals:
  default:
    journal: "~/.local/share/jrnl/journal.md"
linewrap: 79
tagsymbols: '#@'
template: "~/.local/share/jrnl/template.md"
timeformat: '%H:%M %d.%m.%Y'
version: v4.1
